<?php
namespace Representations;

use Drest\Client\Representation;

use Drest\Client\Representation\Json;

/**
 * DO NOT TOUCH THIS
 * This class is generated by CLI-TOOL
 * @author Lee
 */
class UserJson extends Representation
{

    /**
     * @var integer $id
     */
    public $id;

    /**
     * @var array $profile
     */
    public $profile;

    /**
     * @var array $phone_numbers
     */
    public $phone_numbers;

    /**
     * @var string $username
     */
    public $username;

    /**
     * @var string $email_address
     */
    public $email_address;



}