<?php
namespace Reps;


/**
 * DO NOT TOUCH THIS
 * This class is generated by CLI-TOOL
 * @author Lee
 */
class User
{


    public function __construct(\Drest\Representation\AbstractRepresentation $representation)
    {
        $this->_d_rep = $representation;
    }

    /**
     * @var integer $id
     */
    public $id;

    /**
     * @var Reps\Profile $profile
     */
    public $profile;

    /**
     * @var array $phone_numbers
     */
    public $phone_numbers;

    /**
     * @var string $username
     */
    public $username;

    /**
     * @var string $email_address
     */
    public $email_address;


    private $_d_rep;



    // Anything that is exposed and set as a *ToMany should have collection injectors (set as \Doctrine\Common\Collection\ArrayCollection)

    // Any relation that is a *ToOne should be correctly annotated and have an available setter


    /**
     *
     * Get this objects representation
     * @return
     */
    public function getRepresentation()
    {

    }
}